#!/usr/bin/env dotnet run

#:package Spectre.Console

using System.Text.RegularExpressions;
using Spectre.Console;

/// <summary>
/// Git commit-msg hook to validate Conventional Commits format.
/// 
/// Usage: dotnet scripts/ValidateCommitMessage.cs <commit-msg-file>
/// 
/// Format: <type>(<scope>): <description>
/// Example: feat(ui): add dark mode support
/// </summary>
class ValidateCommitMessage
{
    static readonly string[] ValidTypes = new[]
    {
        "feat",     // New feature
        "fix",      // Bug fix
        "docs",     // Documentation
        "style",    // Code style (formatting, no logic change)
        "refactor", // Refactoring
        "perf",     // Performance improvement
        "test",     // Adding tests or fixing tests
        "build",    // Build system or dependencies
        "ci",       // CI/CD changes
        "chore",    // Routine tasks, maintenance
        "revert",   // Revert previous commit
        "wip",      // Work in progress (use sparingly)
    };

    static readonly Regex CommitPattern = new Regex(
        @"^(?<type>feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\((?<scope>[a-z0-9\-]+)\))?:\s+(?<description>.+)$",
        RegexOptions.None
    );

    static int Main(string[] args)
    {
        try
        {
            // Handle --help flag
            if (args.Length > 0 && (args[0] == "--commit-format" || args[0] == "-h"))
            {
                ShowHelp();
                return 0;
            }

            if (args.Length == 0)
            {
                AnsiConsole.MarkupLine("[red]❌ Error: Commit message file not provided[/]");
                return 1;
            }

            var commitMsgFile = args[0];
            if (!File.Exists(commitMsgFile))
            {
                AnsiConsole.MarkupLine($"[red]❌ Error: File not found: {commitMsgFile}[/]");
                return 1;
            }

            var commitMessage = File.ReadAllText(commitMsgFile).Trim();

            // Extract first line for validation (subject line)
            var firstLine = commitMessage.Split('\n')[0].Trim();

            // Skip merge commits and revert commits generated by Git
            if (firstLine.StartsWith("Merge") || firstLine.StartsWith("Revert"))
            {
                AnsiConsole.MarkupLine("[green]✅ Merge/Revert commit - validation skipped[/]");
                return 0;
            }

            // Validate format
            var match = CommitPattern.Match(firstLine);
            if (!match.Success)
            {
                ShowError(firstLine);
                return 1;
            }

            var type = match.Groups["type"].Value;
            var scope = match.Groups["scope"].Value;
            var description = match.Groups["description"].Value;

            // Enforce lowercase type per convention
            if (type != type.ToLowerInvariant())
            {
                ShowError(firstLine, "Type must be lowercase (e.g., 'feat', not 'FEAT')");
                return 1;
            }

            // Validate description length
            if (description.Length < 3)
            {
                ShowError(firstLine, "Description is too short (minimum 3 characters)");
                return 1;
            }

            if (description.Length > 100)
            {
                AnsiConsole.MarkupLine($"[yellow]⚠️  Warning: Description is very long ({description.Length} characters, recommended: ≤100)[/]");
            }

            // Rule: No terminal period at end of description
            if (description.EndsWith('.'))
            {
                ShowError(firstLine, "Do not end description with a period (.)");
                return 1;
            }

            // Success
            AnsiConsole.MarkupLine($"[green]✅ Valid commit message:[/] [cyan]{type}[/]" +
                (string.IsNullOrEmpty(scope) ? "" : $"[grey]({scope})[/]") +
                $": [white]{description}[/]");

            return 0;
        }
        catch (Exception ex)
        {
            AnsiConsole.MarkupLine($"[red]❌ Error: {ex.Message}[/]");
            return 1;
        }
    }

    static void ShowError(string firstLine, string? customMessage = null)
    {
        var issueDetails = customMessage ?? DetectIssue(firstLine);

        Console.WriteLine($"Commit validation failed: {issueDetails}");
        Console.WriteLine($"Your subject: {firstLine}");
        Console.WriteLine("Run 'dotnet scripts/ValidateCommitMessage.cs --commit-format' for format details");
    }

    static void ShowHelp()
    {
        var panel = new Panel(
            new Markup(
                "[cyan]Required format:[/]\n" +
                "[white]<type>(<scope>): <description>[/]\n\n" +
                "[cyan]Examples:[/]\n" +
                "  • [green]feat(ui): add dark mode support[/]\n" +
                "  • [green]fix(api): resolve null reference in user service[/]\n" +
                "  • [green]docs: update README with installation steps[/]\n" +
                "  • [green]refactor: simplify authentication logic[/]\n\n" +
                "[cyan]Valid types:[/]\n" +
                $"  {string.Join(", ", ValidTypes.Select(t => $"[green]{t}[/]"))}\n\n" +
                "[grey]Scope is optional, but recommended for context[/]\n" +
                "[grey]Description: 3-100 characters recommended; do not end with a period[/]"
            )
        )
        {
            Header = new PanelHeader("📋 Conventional Commits Format", Justify.Center),
            Border = BoxBorder.Rounded,
            BorderStyle = new Style(Color.Cyan1)
        };

        AnsiConsole.Write(panel);
    }

    static string DetectIssue(string firstLine)
    {
        // Check for missing colon
        if (!firstLine.Contains(':'))
            return "Missing colon (:) after type/scope!";

        // Check if type is present
        var typeMatch = new Regex(@"^([a-z]+)", RegexOptions.IgnoreCase).Match(firstLine);
        if (!typeMatch.Success)
            return "Commit type is missing!";

        var detectedType = typeMatch.Groups[1].Value.ToLower();
        if (!ValidTypes.Contains(detectedType))
            return $"Invalid type '{detectedType}'!";

        // Check for space after colon
        var colonIndex = firstLine.IndexOf(':');
        if (colonIndex < firstLine.Length - 1 && firstLine[colonIndex + 1] != ' ')
            return "Missing space after colon!";

        // Check for description
        var afterColon = firstLine.Substring(colonIndex + 1).Trim();
        if (string.IsNullOrEmpty(afterColon))
            return "Description is missing after colon!";

        // Check terminal period
        if (afterColon.EndsWith('.'))
            return "Do not end description with a period (.)!";

        return "Invalid commit message format!";
    }
}
